name: Firmware build

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/firmware_build.yml'
      - 'firmware/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/firmware_build.yml'
      - 'firmware/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO project
        run: pio run -v
        working-directory: ./firmware

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            ./firmware/.pio/build/beetle/firmware.hex
            ./firmware/.pio/build/leonardo/firmware.hex
            ./firmware/.pio/build/promicro16/firmware.hex
            ./firmware/.pio/build/esp32-c3-supermini/firmware.hex
          retention-days: 7
