name: Plugin build

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/plugin_build.yml'
      - 'plugin/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/plugin_build.yml'
      - 'plugin/**'
  workflow_dispatch:

jobs:  
  build:    
    runs-on: windows-2022
    
    steps:      
      - uses: actions/checkout@v3
 
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Fetch prerequisites
        run: |
          Invoke-WebRequest -Uri https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip?raw=true -OutFile FanControl.zip
          7z e FanControl.zip FanControl.Plugins.dll
        working-directory: ./plugin

      - name: Build solution
        run: msbuild.exe UsbFanPlugin.sln -property:platform="Any CPU" -property:configuration="Release"
        working-directory: ./plugin

      - uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: ./plugin/UsbFanPlugin/bin/Release/FanControl.UsbFanPlugin.dll
          retention-days: 7
